<?php

use srag\Plugins\SrCurriculum\ObjectSettings\ObjectSettings;
use srag\Plugins\SrCurriculum\Utils\SrCurriculumTrait;
use srag\DIC\SrCurriculum\DICTrait;

/**
 * Class ilObjSrCurriculum
 *
 * Generated by SrPluginGenerator v2.1.0
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
class ilObjSrCurriculum extends ilObjectPlugin
{

    use DICTrait;
    use SrCurriculumTrait;

    const PLUGIN_CLASS_NAME = ilSrCurriculumPlugin::class;
    /**
     * @var ObjectSettings
     */
    protected $object_settings;


    /**
     * ilObjSrCurriculum constructor
     *
     * @param int $a_ref_id
     */
    public function __construct(/*int*/ $a_ref_id = 0)
    {
        parent::__construct($a_ref_id);
    }


    /**
     * @inheritDoc
     */
    public function doCreate()/* : void*/
    {
        $this->object_settings = new ObjectSettings();

        $this->object_settings->setObjId($this->id);

        self::srCurriculum()->objectSettings()->storeObjectSettings($this->object_settings);
    }


    /**
     * @inheritDoc
     */
    public function doDelete()/* : void*/
    {
        if ($this->object_settings !== null) {
            self::srCurriculum()->objectSettings()->deleteObjectSettings($this->object_settings);
        }
    }


    /**
     * @inheritDoc
     */
    public function doRead()/* : void*/
    {
        $this->object_settings = self::srCurriculum()->objectSettings()->getObjectSettingsById(intval($this->id));
    }


    /**
     * @inheritDoc
     */
    public function doUpdate()/* : void*/
    {
        self::srCurriculum()->objectSettings()->storeObjectSettings($this->object_settings);
    }


    /**
     * @inheritDoc
     */
    public final function initType()/* : void*/
    {
        $this->setType(ilSrCurriculumPlugin::PLUGIN_ID);
    }


    /**
     * @return bool
     */
    public function isOnline() : bool
    {
        return $this->object_settings->isOnline();
    }


    /**
     * @param bool $is_online
     */
    public function setOnline(bool $is_online = true)/* : void*/
    {
        $this->object_settings->setOnline($is_online);
    }

    /**
     * @return int
     */
    public function getStartNodeRefId() : int
    {
        return $this->object_settings->getStartNodeRefId();
    }

    /**
     * @param int $start_node_ref_id
     */
    public function setStartNodeRefId(int $start_node_ref_id)/* : void*/
    {
        $this->object_settings->setStartNodeRefId($start_node_ref_id);
    }

    /**
     * @return ObjectSettings
     */
    public function getObjectSettings() : ObjectSettings
    {
        return $this->object_settings;
    }




    /**
     * @inheritDoc
     *
     * @param ilObjSrCurriculum $new_obj
     */
    protected function doCloneObject(/*ilObjSrCurriculum*/ $new_obj, /*int*/ $a_target_id, /*?int*/ $a_copy_id = null)/* : void*/
    {
        $new_obj->object_settings = self::srCurriculum()->objectSettings()->cloneObjectSettings($this->object_settings);

        $new_obj->object_settings->setObjId($new_obj->id);

        self::srCurriculum()->objectSettings()->storeObjectSettings($new_obj->object_settings);
    }
}
