<?php

require_once __DIR__ . "/../vendor/autoload.php";

use srag\Plugins\SrCurriculum\Config\ConfigCtrl;
use srag\Plugins\SrCurriculum\Utils\SrCurriculumTrait;
use srag\DIC\SrCurriculum\DICTrait;


/**
 * Class ilSrCurriculumConfigGUI
 *
 * Generated by SrPluginGenerator v2.1.0
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
class ilSrCurriculumConfigGUI extends ilPluginConfigGUI
{

    use DICTrait;
    use SrCurriculumTrait;

    const CMD_CONFIGURE = "configure";
    const PLUGIN_CLASS_NAME = ilSrCurriculumPlugin::class;


    /**
     * ilSrCurriculumConfigGUI constructor
     */
    public function __construct()
    {

    }


    /**
     * @inheritDoc
     */
    public function performCommand(/*string*/ $cmd)/* : void*/
    {
        $this->setTabs();

        $next_class = self::dic()->ctrl()->getNextClass($this);

        switch (strtolower($next_class)) {
            case strtolower(ConfigCtrl::class):
                self::dic()->ctrl()->forwardCommand(new ConfigCtrl());
                break;

            default:
                $cmd = self::dic()->ctrl()->getCmd();

                switch ($cmd) {
                    case self::CMD_CONFIGURE:
                        $this->{$cmd}();
                        break;

                    default:
                        break;
                }
                break;
        }
    }


    /**
     *
     */
    protected function configure()/* : void*/
    {
        self::dic()->ctrl()->redirectByClass(ConfigCtrl::class, ConfigCtrl::CMD_CONFIGURE);
    }


    /**
     *
     */
    protected function setTabs()/* : void*/
    {
        ConfigCtrl::addTabs();

        self::dic()->locator()->addItem(ilSrCurriculumPlugin::PLUGIN_NAME, self::dic()->ctrl()->getLinkTarget($this, self::CMD_CONFIGURE));
    }
}
