<?php

namespace srag\Plugins\SrCurriculum\Config;

use srag\Plugins\SrCurriculum\Config\Form\FormBuilder;
use srag\Plugins\SrCurriculum\Utils\SrCurriculumTrait;
use ilSrCurriculumPlugin;
use srag\ActiveRecordConfig\SrCurriculum\Config\AbstractFactory;

/**
 * Class Factory
 *
 * Generated by SrPluginGenerator v2.1.0
 *
 * @package srag\Plugins\SrCurriculum\Config
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
final class Factory extends AbstractFactory
{

    use SrCurriculumTrait;

    const PLUGIN_CLASS_NAME = ilSrCurriculumPlugin::class;
    /**
     * @var self|null
     */
    protected static $instance = null;


    /**
     * Factory constructor
     */
    protected function __construct()
    {
        parent::__construct();
    }


    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }


    /**
     * @param ConfigCtrl $parent
     *
     * @return FormBuilder
     */
    public function newFormBuilderInstance(ConfigCtrl $parent) : FormBuilder
    {
        $form = new FormBuilder($parent);

        return $form;
    }
}
