<?php

namespace srag\Plugins\SrCurriculum;

use srag\Plugins\SrCurriculum\Config\Repository as ConfigRepository;
use srag\Plugins\SrCurriculum\ObjectSettings\Repository as ObjectSettingsRepository;
use srag\Plugins\SrCurriculum\Utils\SrCurriculumTrait;
use ilSrCurriculumPlugin;
use srag\DIC\SrCurriculum\DICTrait;

/**
 * Class Repository
 *
 * Generated by SrPluginGenerator v2.1.0
 *
 * @package srag\Plugins\SrCurriculum
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
final class Repository
{

    use DICTrait;
    use SrCurriculumTrait;

    const PLUGIN_CLASS_NAME = ilSrCurriculumPlugin::class;
    /**
     * @var self|null
     */
    protected static $instance = null;


    /**
     * Repository constructor
     */
    private function __construct()
    {

    }


    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }


    /**
     * @return ConfigRepository
     */
    public function config() : ConfigRepository
    {
        return ConfigRepository::getInstance();
    }


    /**
     *
     */
    public function dropTables()/* : void*/
    {
        $this->config()->dropTables();
        $this->objectSettings()->dropTables();
    }


    /**
     *
     */
    public function installTables()/* : void*/
    {
        $this->config()->installTables();
        $this->objectSettings()->installTables();
    }


    /**
     * @return ObjectSettingsRepository
     */
    public function objectSettings() : ObjectSettingsRepository
    {
        return ObjectSettingsRepository::getInstance();
    }
}
